### ISSUE TITLE
`layout-manager:maximize` in readme

### ISSUE THREAD

**Issue by diiq** [santip/layout-manager#1]
![screenshot 2014-04-18 11 30 46](https://cloud.githubusercontent.com/assets/150973/2743127/8acf3196-c70e-11e3-8b5c-107dd44bb8d7.png)

The readme uses the command `layout-manager:maximize` but I think it means `layout-manager:maximize-active-pane`. Threw me for a loop, because my `cmd-shift-enter` is already occupied :)

**Comment by santip** [comment]
Ahh, good catch, I renamed them as part of a refactoring where I also created separate packages for each feature (to aid in package discoverability).

I'll release a fixed patch in a few minutes, adding links to the individual packages as well.

Thanks.
